name: deploy-prod

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, World! ${GITHUB_REF#refs/heads/} ${GITHUB_REF##*/}
